# Generated by Django 3.0.4 on 2020-03-16 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardTemplate',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('board_state', models.TextField()),
                ('board_width', models.IntegerField()),
                ('board_height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('public_spectators', models.BooleanField(default=False)),
                ('board_state', models.TextField()),
                ('board_width', models.IntegerField()),
                ('board_height', models.IntegerField()),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admingames', to=settings.AUTH_USER_MODEL)),
                ('base_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gameInstances', to='tabletops.BoardTemplate')),
                ('whitelist', models.ManyToManyField(related_name='gamerooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='tabletops.GameRoom')),
            ],
        ),
    ]
