# Generated by Django 3.0.4 on 2020-03-18 18:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tabletops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GameMessages', to='tabletops.GameRoom')),
            ],
        ),
    ]
