# Generated by Django 3.0.4 on 2020-03-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabletops', '0002_gamemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardtemplate',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
