# Generated by Django 3.0.4 on 2020-03-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabletops', '0003_boardtemplate_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='off_board',
            field=models.TextField(default='[]'),
        ),
    ]
