# Generated by Django 3.0.4 on 2020-03-13 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='messageTime',
            new_name='time',
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.ChatRoom'),
            preserve_default=False,
        ),
    ]
